Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64" # need at least Python 3.7
  config.vm.synced_folder "../", "/home/vagrant/odm360"
  config.vm.provision "shell", inline: <<-SCRIPT
    sudo apt-get update
    sudo apt-get install -y devscripts git
    cd /home/vagrant/odm360
    yes | sudo mk-build-deps -ri
SCRIPT
end
